#!/bin/bash
##################################################
#Script Name  : I Booted
#Description  : Send an email alert when system boots
#Args         : none
#Author       : Tim West
#Email        : tim@greenmtnitsolutions.com
##################################################

#Put this in your crontab with the @reboot timer so it runs on each boot
#@reboot /usr/bin/ibooted

##################################################
#VARIABLES
##################################################
#Set a friendlier hostname if you want by commenting out the default and uncommenting and editing the next line with a custom name.
MYHOSTNAME="$HOSTNAME"
#MYHOSTNAME="CompanyBackupServer"

#Destination email address for the alerts
EMAILDEST="info@greenmtnitsolutions.com"

#########################
#Variables below this line generally don't need to be changed

#Subject of the alert email.
EMAILSUBJ="Subject: System Boot Alert for $MYHOSTNAME"

#Get the time
NOW=$(date)

#Set the email body.
EMAILMESSAGE="The System $MYHOSTNAME has just booted at $NOW. If you did not initiate this reboot, you should check for issues."

##################################################
#FUNCTIONS
##################################################

#Function to send email
send_email () {
 echo "$EMAILMESSAGE" | mail -s "$EMAILSUBJ" info@greenmtnitsolutions.com
 }

##################################################
#ACTIONS
##################################################

#Send the email
send_email

