#!/bin/bash
dest_addr="recipient@yourdomain.com"

send_email() {
  local subject
  subject="Scheduled PVE Status Report From $(hostname -f)"
  #echo "$message" | mail -s "$subject" "$dest_addr" -A "$report"
  cat $tmpfile | mail -s "$subject" "$dest_addr"
}

tmpfile=$(mktemp)
/usr/bin/status_report > $tmpfile
send_email
rm $tmpfile
